name = "Seymour"
defaultTargets = ["Seymour"]

[leanOptions]
autoImplicit = false
relaxedAutoImplicit = false
pp.structureInstances = false
pp.numericProj.prod = false

[[require]]
name = "linters"
git = "https://github.com/madvorak/leanters"
rev = "main"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "b06bfd2a5e627b3dd3ae90fdb095cbd9413bb23b"

[[lean_lib]]
name = "Seymour"
